import { Bool, OpenAPIRoute, Str } from "chanfana";
import { z } from "zod";
import { type AppContext } from "../types";

export class CrunchyrollFetch extends OpenAPIRoute {
	schema = {
		tags: ['Crunchyroll'],
		summary: 'Get a single Task by slug',
		request: {
			params: z.object({
				id: Str({description: 'Crunchyroll ID'}),
				lang: Str({description: 'Subtitle language'}),
			}),
		},
		responses: {
			'200': {
				description: 'Returns a single task if found',
				content: {
					'text/plain': {
						schema: z.string(),
					},
				},
			},
			'404': {
				description: 'Task not found',
				content: {
					'application/json': {
						schema: z.object({
							series: z.object({
								success: Bool(),
								error: Str(),
							}),
						}),
					},
				},
			},
		},
	};

	async handle(c: AppContext) {
		const data = await this.getValidatedData<typeof this.schema>();

		const { id, lang } = data.params;

		console.log(id, lang)
		if (id !== 'G9DUE19E9' && lang !== 'hu-HU') {
			return Response.json(
				{
					success: false,
					error: 'Object not found',
				},
				{
					status: 404,
				},
			);
		}

		return c.text(`[Script Info]
; Script generated by Aegisub master r8903+1 g1042226, line0
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Video File: ?dummy:23.976000:40000:1920:1080:47:163:254:
Video AR Value: 1.777778
Video Zoom Percent: 0.625000
Active Line: 1
Video Position: 120

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Cronos Pro Light Display,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: title,Gothic725 Blk BT,50,&H00000000,&H000000FF,&H000066FF,&HBE000000,-1,0,0,0,100,100,0,0,1,0,0,5,15,15,15,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,Árvíztűrőtükörfúrógép—
Dialogue: 0,0:00:05.00,0:00:10.00,Default,,0,0,0,,♪ Nagyon zenés zene ♪
`)
	}
}
